[build]
  publish = "."

[build.environment]
  NODE_VERSION = "18"

[[headers]]
  for = "/*"
  [headers.values]
    Permissions-Policy = "camera=*"
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type"
    X-Frame-Options = "SAMEORIGIN"
    X-Content-Type-Options = "nosniff"

[[headers]]
  for = "*.js"
  [headers.values]
    Content-Type = "application/javascript"

[[headers]]
  for = "*.css"
  [headers.values]
    Content-Type = "text/css"

[[headers]]
  for = "*.glb"
  [headers.values]
    Content-Type = "model/gltf-binary"

[[headers]]
  for = "*.gltf"
  [headers.values]
    Content-Type = "model/gltf+json"

[[redirects]]
  from = "/marcador"
  to = "/marcador-hiro.html"
  status = 200

[[redirects]]
  from = "/custom"
  to = "/index-custom-marker.html"
  status = 200 